name: Combined UI and API Testing

on:
  push:
    branches: [ "204165T-2" ]
  pull_request:
    branches: [ "204165T-2" ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  ui-testing:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: UI-Testing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'yarn'
          cache-dependency-path: 'UI-Testing/yarn.lock'

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Install xvfb
        run: sudo apt-get install -y xvfb

      - name: Run Playwright tests
        run: xvfb-run --auto-servernum yarn test
        continue-on-error: true
        env:
          CI: true

      - name: Generate UI Allure Report
        run: yarn allure:generate
        if: always()

      - name: Upload UI Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ui-allure-results
          path: UI-Testing/allure-report
          retention-days: 30

  api-testing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          java-version: '20'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        working-directory: API_Testing
        run: mvn clean compile -DskipTests
        continue-on-error: true

      - name: Start Application
        working-directory: API_Testing
        run: |
          cd libs
          java -Dserver.port=7081 -jar demo-0.0.1-SNAPSHOT.jar &
          echo "Waiting for application to start..."
          USERNAME="admin"
          PASSWORD="password"
          AUTH=$(echo -n "$USERNAME:$PASSWORD" | base64)
          timeout 60 bash -c "while [[ \"\$(curl -s -o /dev/null -w '%{http_code}' -H \"Authorization: Basic $AUTH\" 127.0.0.1:7081/api/books)\" != \"200\" ]]; do sleep 5; done" || true
          echo "Application is running!"
          cd ..
        continue-on-error: true

      - name: Run API Tests
        id: api-tests
        working-directory: API_Testing
        run: mvn test
        continue-on-error: true

      - name: Generate API Allure Report
        if: always()
        working-directory: API_Testing
        run: mvn allure:report
        continue-on-error: true

      - name: Upload API Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: api-allure-results
          path: API_Testing/target/site/allure-maven-plugin
          retention-days: 30

  combine-reports:
    needs: [ui-testing, api-testing]
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Download UI Results
        uses: actions/download-artifact@v3
        with:
          name: ui-allure-results
          path: combined-report/ui

      - name: Download API Results
        uses: actions/download-artifact@v3
        with:
          name: api-allure-results
          path: combined-report/api

      - name: Combine Reports
        run: |
          mkdir -p combined-report/merged
          echo "<html><head><title>Combined Test Reports</title></head><body>" > combined-report/merged/index.html
          echo "<h1>Combined Test Reports</h1>" >> combined-report/merged/index.html
          echo "<h2><a href='ui/'>UI Test Report</a></h2>" >> combined-report/merged/index.html
          echo "<h2><a href='api/'>API Test Report</a></h2>" >> combined-report/merged/index.html
          echo "</body></html>" >> combined-report/merged/index.html
          cp -r combined-report/ui combined-report/merged/ui
          cp -r combined-report/api combined-report/merged/api
          touch combined-report/merged/.nojekyll

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: combined-report/merged

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        if: always()

      - name: Print Test Status
        if: always()
        run: |
          echo "Test execution completed"
          echo "Combined report should be available at: ${{ steps.deployment.outputs.page_url }}"
